# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class SkuName(Enum):

    classic = "Classic"
    basic = "Basic"
    standard = "Standard"
    premium = "Premium"


class SkuTier(Enum):

    classic = "Classic"
    basic = "Basic"
    standard = "Standard"
    premium = "Premium"


class ProvisioningState(Enum):

    creating = "Creating"
    updating = "Updating"
    deleting = "Deleting"
    succeeded = "Succeeded"
    failed = "Failed"
    canceled = "Canceled"


class PasswordName(Enum):

    password = "password"
    password2 = "password2"


class RegistryUsageUnit(Enum):

    count = "Count"
    bytes = "Bytes"


class WebhookStatus(Enum):

    enabled = "enabled"
    disabled = "disabled"


class WebhookAction(Enum):

    push = "push"
    delete = "delete"


class BuildDefinitionStatus(Enum):

    disabled = "Disabled"
    enabled = "Enabled"


class SourceControlTypes(Enum):

    github = "Github"
    visual_studio_team_service = "VisualStudioTeamService"


class BuildStatus(Enum):

    queued = "Queued"
    started = "Started"
    running = "Running"
    succeeded = "Succeeded"
    failed = "Failed"
    cancelled = "Cancelled"


class BuildType(Enum):

    auto_build = "AutoBuild"
    quick_build = "QuickBuild"


class TokenType(Enum):

    pat = "PAT"
    oauth = "OAuth"


class OsTypes(Enum):

    windows = "Windows"
    linux = "Linux"
